# Generated by Django 3.0.2 on 2020-01-26 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 26, 10, 32, 44, 768311, tzinfo=utc)),
        ),
    ]
